version: "3.8"
services:
  frontend:
    container_name: ydenn_landing_frontend
    image: node:alpine
    working_dir: /srv/app
    command: ["sh", "-c", "npm install && npm run dev"]
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
    tty: true
    expose:
      - 5000
    ports:
      - "5000:5000"

  backend:
    container_name: ydenn_landing_backend
    image: node:alpine
    working_dir: /home/node/app
    env_file:
      - ./backend/.env
    command: ["sh", "-c", "npm install && npm start"]
    volumes:
      - type: bind
        source: ./backend/src
        target: /home/node/app
    expose:
      - 3000
    ports:
      - "3000:3000"
